### PR TITLE
Fix dirty triggering with existing custom context

### PR DESCRIPTION
**Pull request by eugen0329**
This PR solves #811 issue.

### CODE REVIEW

**Comment by eugen0329** [comment]
Oh, everything was well locally :(

BTW the problem with dirty status still remains. Can you, please, clarify what was the original purpose of a custom context check [here](https://github.com/mbleigh/acts-as-taggable-on/pull/812/files#diff-6fb8d10ba793f1b09e64f2923988ee4eL327)?

**Comment by Erowlin** [comment]
Hey, thanks for the fix @eugen0329 !
What's the status of this one? We really need a fix on our application codebase :).

Also, it looks similar to #723 and #728.

Thanks a lot !

**Comment by marlonmarcos21** [comment]
@mbleigh Are you looking into this? This is still broken and this PR actually fixes it. Specs are fine locally for me too.

**Comment by travisofthenorth** [comment]
+1. This is a pretty big issue and it would be great to have it fixed.

**Comment by seuros** [comment]
This PR is not current anymore.

**Comment by ivanovv** [comment]
@seuros I'm sorry to ask in a closed issue, but is there a version of this gem that works fine with Rails 4.2? We are quite lagging with updates to Rails 5, hence my question.

Also, is there a workaround for #811 that I can implement in app code?

**Comment by seuros** [comment]
@ivanovv I think version 5.0.0 has the fix. Did you try it ?

**Comment by ivanovv** [comment]
@seuros my bad, I've read this commit message

> Drop support for old version of ActiveRecord and Ruby

and made an incorrect assumption (Rails v5 or later)

Will give it a go!

**Comment by ivanovv** [comment]
Looks like the fix never made it into v5 https://github.com/mbleigh/acts-as-taggable-on/compare/v4.0.0...v5.0.0

My specs also fail.

**Pull request closed without merging**
