### PR TITLE
Add rspecs to tagging spec

### PR DESCRIPTION
**Pull request by pcupueran**
I completed the test that were pending in the tagging_spec file. This helps to maintain the code

### CODE REVIEW

**Comment by seuros** [comment]
can you squash your commits ?

**Comment by pcupueran** [comment]
Hi Seuros, Ok I will squash them

**Comment by seuros** [comment]
Awesome :green_heart:  
Thank you @pcupueran

**Comment by dmgarland** [comment]
Well done Patty!

**Comment by SimonDKnight** [comment]
Nice addition Patty!

**Comment by pcupueran** [comment]
Thank you!

**Pull request merged**
