### PR TITLE
Given a resource: get all tags by owner and get owner tags for multiple contexts

### PR DESCRIPTION
**Pull request by brilyuhns**
This allows to
- Retrieve all the tags to a resource by an owner in one go
- Retrieve owner tags by multiple context in one go

### CODE REVIEW

**Comment by seuros** [comment]
LGTM

@krzysiek1507 @rbritom ^^

**Comment by krzysiek1507** [comment]
@brilyuhns could you please add specs?

**Comment by brilyuhns** [comment]
Hey thanks for considering this. I will write some specs soon and update the PR.

**Comment by seuros** [comment]
@brilyuhns it seem that either your git client or github is not configured correctly.
The commits don't link to your profile. 
I can merge, but your profile won't show up in the contributors part.

**Comment by seuros** [comment]
Thank you @brilyuhns

**Comment by brilyuhns** [comment]
Thanks for the gem :)

**Pull request merged**
