### PR TITLE
Add Rails 6.1 support

### PR DESCRIPTION
**Pull request by kvokka**
By the way switch from using rails6.0.beta1 to released version in CI

### CODE REVIEW

**Comment by cantino** [comment]
Yes please!

**Comment by silva96** [comment]
why there are 3 pr for rails 6.1 support?

**Comment by kvokka** [comment]
@silva96  at the moment of  this branch creation, PR #1012 was not actually using rails 6.1 gemfiles and in fact it was not working, unfortunately, that pushed me to create this PR

idk why #1015 was created, can only say, that it will not work correctly (you will see it in CI, which by the way runs forever). It has a few issues, which are fixed in this PR.

**Comment by silva96** [comment]
@kvokka thanks for the explanation

**Comment by silva96** [comment]
@mbleigh do you mind take a look here?

**Comment by mbleigh** [comment]
Sorry, I haven't been the maintainer of this library for 5+ years 😅  I'm actually not even sure who is the primary maintainer these days.

**Comment by mkilling** [comment]
@seuros do you by any chance know who currently maintains this repo?

**Comment by seuros** [comment]
@mkilling , Sorry i missed this PR.  I will check it and release a new version.

**Comment by seuros** [comment]
If there is no regression in master, this will be released by end of week. 
I don't see any warning.

**Comment by mrbongiolo** [comment]
Thank you @seuros !!

**Comment by silva96** [comment]
Merry christmas!
@seuros  any update with the release?

**Pull request merged**
