### PR TITLE
Add Rails 7.2.0 support

### LINKED ISSUE #1130: Issue on rails 7.2 update
Updated Rails and active record

`Because acts-as-taggable-on >= 10.0.0 depends on activerecord >= 6.1, < 7.2 and rails >= 7.2.0 depends on activerecord = 7.2.0, acts-as-taggable-on >= 10.0.0 is incompatible with rails >= 7.2.0. So, because Gemfile depends on rails ~> 7.2.0 and Gemfile depends on acts-as-taggable-on ~> 10.0, version solving has failed.`

Seems act-as-taggable-on activerecord dependency wants < 7.2 but with rails update it ends up with = 7.2

### PR DESCRIPTION
**Pull request by adbelsham**
As per the title, needed Rails 7.2.0 support so I added it.  Thanks!

Fixes #1130 (not my issue but coincidentally fixes this so tagging it in).

### CODE REVIEW

**Comment by foton** [comment]
Yes , please merge it. As result of upgrade to Rail 7.2 ,  bundler replaces `act-as-taggable` version 10.0 with 5.0 (which do not have top version constraint)!

**Comment by seuros** [comment]
Test are not passing.

**Comment by adbelsham** [comment]
> Test are not passing.

Tests aren’t passing on master anyway.

Maintainer can resolve that, or I can look at it as a separate PR.  Upgrading to rails 7 doesn’t create the failures.

**Comment by seuros** [comment]
Error happen only in 7.2 https://github.com/mbleigh/acts-as-taggable-on/pull/1132.

I removed all the version that reached EOL.

**Pull request closed without merging**
