### PR TITLE
Add context constraint to find_related_* methods. 

### PR DESCRIPTION
**Pull request by d4rky-pl**
Fix for issue #628
(I'm terribly sorry for the mess, I keep forgetting it's impossible to convert issue into pull request)

### CODE REVIEW

**Comment by seuros** [comment]
could you add a test for this ?

**Comment by d4rky-pl** [comment]
Test added

**Comment by seuros** [comment]
Could you squash the commits ?

**Comment by d4rky-pl** [comment]
done

**Comment by seuros** [comment]
:green_heart:

**Comment by d4rky-pl** [comment]
I would be very grateful for releasing a new minor version with this fix as it's affecting my client's important part of project.

**Comment by seuros** [comment]
Will do

**Comment by d4rky-pl** [comment]
@seuros any idea when? ;)

**Comment by seuros** [comment]
Sorry for delay. Tagged and released.

**Pull request merged**
